name: haldo-werld
run-name: ${{ github.actor }} is writing a new action
on: [push]
jobs:
  check-bats-version:
    runs-on: 
    steps:
      - uses: actions/checkout@v4
      # - uses: actions/setup-node@v4
        # with:
        #   node-version: '20'
      # - run: npm install -g bats
      - run: whoami
      - run: echo "Haldo Werld"
      - run: pwd
      - run: ls

