name: haldo-werld
run-name: ${{ github.actor }} is writing a new action
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: whoami
      - run: echo Haldo
